call bundle install --path=vendor/bundle --jobs=3
call npm install --save-dev grunt
call npm install --save-dev grunt-contrib-jshint
call npm install --save-dev grunt-mocha-istanbul
call npm install --save-dev sinon-chai
call npm install --save-dev grunt-este-watch
call bower install --save foundation
call bower install --save fontawesome
call bower install --save jquery.kerning
call bower install --save jquery-smooth-scroll
call bower install --save ScrollToFixed
call bower install --save nicescroll
call bower install --save colorbox
call bower install --save sweetalert
