bundle install --path=vendor/bundle --jobs=3
npm install --save-dev grunt
npm install --save-dev grunt-contrib-jshint
npm install --save-dev grunt-mocha-istanbul
npm install --save-dev sinon-chai
npm install --save-dev grunt-este-watch
bower install --save foundation
bower install --save fontawesome
bower install --save jquery.kerning
bower install --save jquery-smooth-scroll
bower install --save ScrollToFixed
bower install --save nicescroll
bower install --save colorbox
bower install --save sweetalert